Portfolio-mobile-version
Gh-Reza/Portfolio pull request #1
Opened 2023-04-26 21:20 UTC by Gh-Reza

## Portfolio-mobile-version

# Changes:

- Added initial files
- Added Linters(Lighthouse, webint, stylelint)
- Customized README.md

2023-04-26 21:43 UTC, zieeco requested changes
Hi @Gh-Reza,


<img height="225" src="https://media4.giphy.com/media/Cm9wKmKMUlRPvdoHgU/giphy-downsized-medium.gif"/>

Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Descriptive PR. ✔️
- Good commit messages :+1: 

## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 21:43 UTC, zieeco commented on index.html
> +    </div>
- Hey, great job so far! however, to enforce good use of the html5 semantic tag, the content here is a group of list items, so you should use a `ul` as the container with an `li` to hold each `a` tags that wrap each `img`
```
<ul>
  <li><a href=""><img src="" alt=""></a></li>
</ul>
```

2023-04-26 21:43 UTC, zieeco commented on index.html
> +  </section>
- Hey, this should be a header tag as this holds the introductory content of your webpage such as the nav items. let's make this a header tag

2023-04-26 21:43 UTC, zieeco commented on index.html
> +    </a>
- Hi, this content should be wrapped in the nav tag as it holds the list of nav items of your webpage. please, let's wrap this content in a nav tag to improve our use of semantic tag.

2023-04-26 21:43 UTC, zieeco commented on style.css
> +
- Hey, according to the list of microverse [HTML & CSS requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md), You should not overuse or use `!important` except you're using a CSS framework that has it applied to styles. let's try to add the styles without making use of it.

2023-04-26 21:43 UTC, zieeco commented on README.md
> +  cd HelloMicroverse
- Hey, let's make this the current project so as not to confuse the users to improve your readme.

2023-04-27 07:04 UTC, amejid approved these changes
Hi @Gh-Reza, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct use of Github flow :heavy_check_mark: 
- Good UI :heavy_check_mark: 
- Nice semantic structure :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 08:30 UTC, merged